INSERT INTO tg_bot.bot (bot_id, bot_username, bot_token, description)
VALUES (1, 'DivinationBot', '', '每日運勢BOT');

INSERT INTO tg_bot.bot (bot_id, bot_username, bot_token, description)
VALUES (2, 'ChangeFileBot', '', '上傳資料BOT');

INSERT INTO tg_bot.language (language_code, language_name, bot_id)
VALUES ('ZH_TW', '繁體中文', 1),
       ('EN', 'English', 1);

INSERT INTO tg_bot.gif (id, bot_id, type, telegram_file_id, description)
VALUES (1, 1, 'CARD_DRAWING_ANIMATION', 'CgACAgUAAxkBAAOfZxhUKD8ZfaYC4QVdLk99javgCnAAAgYUAAJrE8BUHNo1TB9p5x02BA',
        '爆炸');

INSERT INTO tg_bot.gif (bot_id, type, telegram_file_id, description)
VALUES (2, 'QUESTION_ANIMATION', 'CgACAgUAAxkBAAMJZxkOL336vuAEHFtTOiLa6RQO0fEAAigQAAI2fQFUblKUr19mN7o2BA', '烏薩奇蛤');

INSERT INTO tg_bot.manager (bot_id, telegram_id, description)
VALUES (1, '1513052214', 'boss'),
       (2, '1513052214', 'boss');

INSERT INTO tg_bot.text (type, language_type, content)
VALUES ('WELCOME_MESSAGE', 'EN', 'welcome to use daily divination !'),
       ('WELCOME_MESSAGE', 'ZH_TW', '歡迎使用 每日運勢抽獎~');

INSERT INTO tg_bot.text (type, language_type, content)
VALUES ('ASK_FOR_LANGUAGE', 'ZH_TW', '請選擇大哥你想使用的語言~');
INSERT INTO tg_bot.text (type, language_type, content)
VALUES ('ASK_FOR_LANGUAGE', 'EN', 'please choose you favorite language');

# 塔羅sql
-- 插入 Card 表數據
INSERT INTO tg_bot.tarot_card (name, category, description)
VALUES ('愚者', '大阿爾卡納', '愚者牌象徵著冒險與未知的可能性。'),
       ('戰車', '大阿爾卡納', '戰車牌象徵著掌控和勝利。'),
       ('皇后/女帝', '大阿爾卡納', '女帝牌象徵著愛與豐饒。'),
       ('惡魔', '大阿爾卡納', '惡魔牌象徵著誘惑和束縛。'),
       ('正義', '大阿爾卡納', '正義牌象徵著公正和平衡。'),
       ('皇帝', '大阿爾卡納', '皇帝牌象徵著權威與秩序。'),
       ('魔術師', '大阿爾卡納', '魔術師牌象徵著創造和行動。'),
       ('戀人', '大阿爾卡納', '戀人牌象徵著選擇和愛情。'),
       ('死神', '大阿爾卡納', '死神牌象徵著變革和結束。'),
       ('星星', '大阿爾卡納', '星星牌象徵著希望和靈感。'),
       ('教皇', '大阿爾卡納', '教皇牌象徵著指導與道德。'),
       ('隱士', '大阿爾卡納', '隱士牌象徵著內省和探索。'),
       ('太陽', '大阿爾卡納', '太陽牌象徵著快樂和成功。'),
       ('運命之輪', '大阿爾卡納', '運命之輪牌象徵著轉折和命運。'),
       ('世界', '大阿爾卡納', '世界牌象徵著完成和新開始。'),
       ('力量', '大阿爾卡納', '力量牌象徵著勇氣與決心。'),
       ('節制', '大阿爾卡納', '節制牌象徵著平衡與自律。'),
       ('塔', '大阿爾卡納', '塔牌象徵著災難和驚變。'),
       ('月亮', '大阿爾卡納', '月亮牌象徵著迷惑和恐懼。'),
       ('審判', '大阿爾卡納', '審判牌象徵著重新開始和審視。'),
       ('女教皇/女祭司', '大阿爾卡納', '女教皇牌象徵著直覺和智慧。'),
       ('倒吊人', '大阿爾卡納', '倒吊人牌象徵著犧牲和耐心。');


-- 插入 CardPosition 表數據（包含正位和逆位位置及解析類型）
INSERT INTO tg_bot.card_position (card_id, position, interpretation_type)
VALUES (1, 'UPRIGHT', 'CURRENT_SITUATION'),
       (1, 'REVERSED', 'CURRENT_SITUATION'),
       (2, 'UPRIGHT', 'CURRENT_SITUATION'),
       (2, 'REVERSED', 'CURRENT_SITUATION'),
       (3, 'UPRIGHT', 'CURRENT_SITUATION'),
       (3, 'REVERSED', 'CURRENT_SITUATION'),
       (4, 'UPRIGHT', 'CURRENT_SITUATION'),
       (4, 'REVERSED', 'CURRENT_SITUATION'),
       (5, 'UPRIGHT', 'CURRENT_SITUATION'),
       (5, 'REVERSED', 'CURRENT_SITUATION'),
       (6, 'UPRIGHT', 'CURRENT_SITUATION'),
       (6, 'REVERSED', 'CURRENT_SITUATION'),
       (7, 'UPRIGHT', 'CURRENT_SITUATION'),
       (7, 'REVERSED', 'CURRENT_SITUATION'),
       (8, 'UPRIGHT', 'CURRENT_SITUATION'),
       (8, 'REVERSED', 'CURRENT_SITUATION'),
       (9, 'UPRIGHT', 'CURRENT_SITUATION'),
       (9, 'REVERSED', 'CURRENT_SITUATION'),
       (10, 'UPRIGHT', 'CURRENT_SITUATION'),
       (10, 'REVERSED', 'CURRENT_SITUATION'),
       (11, 'UPRIGHT', 'CURRENT_SITUATION'),
       (11, 'REVERSED', 'CURRENT_SITUATION'),
       (12, 'UPRIGHT', 'CURRENT_SITUATION'),
       (12, 'REVERSED', 'CURRENT_SITUATION'),
       (13, 'UPRIGHT', 'CURRENT_SITUATION'),
       (13, 'REVERSED', 'CURRENT_SITUATION'),
       (14, 'UPRIGHT', 'CURRENT_SITUATION'),
       (14, 'REVERSED', 'CURRENT_SITUATION'),
       (15, 'UPRIGHT', 'CURRENT_SITUATION'),
       (15, 'REVERSED', 'CURRENT_SITUATION'),
       (16, 'UPRIGHT', 'CURRENT_SITUATION'),
       (16, 'REVERSED', 'CURRENT_SITUATION'),
       (17, 'UPRIGHT', 'CURRENT_SITUATION'),
       (17, 'REVERSED', 'CURRENT_SITUATION'),
       (18, 'UPRIGHT', 'CURRENT_SITUATION'),
       (18, 'REVERSED', 'CURRENT_SITUATION'),
       (19, 'UPRIGHT', 'CURRENT_SITUATION'),
       (19, 'REVERSED', 'CURRENT_SITUATION'),
       (20, 'UPRIGHT', 'CURRENT_SITUATION'),
       (20, 'REVERSED', 'CURRENT_SITUATION'),
       (21, 'UPRIGHT', 'CURRENT_SITUATION'),
       (21, 'REVERSED', 'CURRENT_SITUATION'),
       (22, 'UPRIGHT', 'CURRENT_SITUATION'),
       (22, 'REVERSED', 'CURRENT_SITUATION'),
       -- 未來解析
       (1, 'UPRIGHT', 'FUTURE_SITUATION'),
       (1, 'REVERSED', 'FUTURE_SITUATION'),
       (2, 'UPRIGHT', 'FUTURE_SITUATION'),
       (2, 'REVERSED', 'FUTURE_SITUATION'),
       (3, 'UPRIGHT', 'FUTURE_SITUATION'),
       (3, 'REVERSED', 'FUTURE_SITUATION'),
       (4, 'UPRIGHT', 'FUTURE_SITUATION'),
       (4, 'REVERSED', 'FUTURE_SITUATION'),
       (5, 'UPRIGHT', 'FUTURE_SITUATION'),
       (5, 'REVERSED', 'FUTURE_SITUATION'),
       (6, 'UPRIGHT', 'FUTURE_SITUATION'),
       (6, 'REVERSED', 'FUTURE_SITUATION'),
       (7, 'UPRIGHT', 'FUTURE_SITUATION'),
       (7, 'REVERSED', 'FUTURE_SITUATION'),
       (8, 'UPRIGHT', 'FUTURE_SITUATION'),
       (8, 'REVERSED', 'FUTURE_SITUATION'),
       (9, 'UPRIGHT', 'FUTURE_SITUATION'),
       (9, 'REVERSED', 'FUTURE_SITUATION'),
       (10, 'UPRIGHT', 'FUTURE_SITUATION'),
       (10, 'REVERSED', 'FUTURE_SITUATION'),
       (11, 'UPRIGHT', 'FUTURE_SITUATION'),
       (11, 'REVERSED', 'FUTURE_SITUATION'),
       (12, 'UPRIGHT', 'FUTURE_SITUATION'),
       (12, 'REVERSED', 'FUTURE_SITUATION'),
       (13, 'UPRIGHT', 'FUTURE_SITUATION'),
       (13, 'REVERSED', 'FUTURE_SITUATION'),
       (14, 'UPRIGHT', 'FUTURE_SITUATION'),
       (14, 'REVERSED', 'FUTURE_SITUATION'),
       (15, 'UPRIGHT', 'FUTURE_SITUATION'),
       (15, 'REVERSED', 'FUTURE_SITUATION'),
       (16, 'UPRIGHT', 'FUTURE_SITUATION'),
       (16, 'REVERSED', 'FUTURE_SITUATION'),
       (17, 'UPRIGHT', 'FUTURE_SITUATION'),
       (17, 'REVERSED', 'FUTURE_SITUATION'),
       (18, 'UPRIGHT', 'FUTURE_SITUATION'),
       (18, 'REVERSED', 'FUTURE_SITUATION'),
       (19, 'UPRIGHT', 'FUTURE_SITUATION'),
       (19, 'REVERSED', 'FUTURE_SITUATION'),
       (20, 'UPRIGHT', 'FUTURE_SITUATION'),
       (20, 'REVERSED', 'FUTURE_SITUATION'),
       (21, 'UPRIGHT', 'FUTURE_SITUATION'),
       (21, 'REVERSED', 'FUTURE_SITUATION'),
       (22, 'UPRIGHT', 'FUTURE_SITUATION'),
       (22, 'REVERSED', 'FUTURE_SITUATION'),
       (1, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (1, 'REVERSED', 'OTHERS_THOUGHT'),
       (2, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (2, 'REVERSED', 'OTHERS_THOUGHT'),
       (3, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (3, 'REVERSED', 'OTHERS_THOUGHT'),
       (4, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (4, 'REVERSED', 'OTHERS_THOUGHT'),
       (5, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (5, 'REVERSED', 'OTHERS_THOUGHT'),
       (6, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (6, 'REVERSED', 'OTHERS_THOUGHT'),
       (7, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (7, 'REVERSED', 'OTHERS_THOUGHT'),
       (8, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (8, 'REVERSED', 'OTHERS_THOUGHT'),
       (9, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (9, 'REVERSED', 'OTHERS_THOUGHT'),
       (10, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (10, 'REVERSED', 'OTHERS_THOUGHT'),
       (11, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (11, 'REVERSED', 'OTHERS_THOUGHT'),
       (12, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (12, 'REVERSED', 'OTHERS_THOUGHT'),
       (13, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (13, 'REVERSED', 'OTHERS_THOUGHT'),
       (14, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (14, 'REVERSED', 'OTHERS_THOUGHT'),
       (15, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (15, 'REVERSED', 'OTHERS_THOUGHT'),
       (16, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (16, 'REVERSED', 'OTHERS_THOUGHT'),
       (17, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (17, 'REVERSED', 'OTHERS_THOUGHT'),
       (18, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (18, 'REVERSED', 'OTHERS_THOUGHT'),
       (19, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (19, 'REVERSED', 'OTHERS_THOUGHT'),
       (20, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (20, 'REVERSED', 'OTHERS_THOUGHT'),
       (21, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (21, 'REVERSED', 'OTHERS_THOUGHT'),
       (22, 'UPRIGHT', 'OTHERS_THOUGHT'),
       (22, 'REVERSED', 'OTHERS_THOUGHT');


INSERT INTO tg_bot.card_interpretation (position_id, content)
VALUES
#  正位的現狀解釋
(1, '現在兩人的關係處在無法確定的狀態。從今往後，考慮一起前往快樂的場所如何?'),
(3, '兩人正處於變化之中。或許你們正在朝向全新關係前進的路上。'),
(5, '目前兩人處於非常滿足的狀態。和他在一起，就能讓你感覺到被充實。'),
(7, '兩個人正互相束縛著。比如說一個蠻橫、一個服從。'),
(9, '兩人處於旗鼓相當的狀態。彼此期望的，也正是對方期望的。'),
(11, '兩人的關係不好不壞，頃向安定的樣子。也不太期望有什麼變化，暫時不會有所變化的吧。'),
(13, '現在兩人的關係才剛剛開始，或許說你們倆雙方都想開始一段，與以往都不一樣的交往關係。'),
(15, '二人的關係正處在關鍵分歧點上，今後也許會發生某些變化，往好的方向。'),
(17, '兩人將迎來巨大的變化。也許迄今為止的關係將畫上句點。'),
(19, '無論現在兩人處於怎樣的狀態，你都始終抱持著對於未來的希望，並接受現狀。'),
(21, '兩個人的關係是認真而克制的。也因如此，趣味性上可能會有所欠缺。不過近期內這種狀態將會持續。'),
(23, '兩個人到了這樣的時期，都著重於重新探尋自己內心的希冀，而忽視於思考與對方的關聯。'),
(25, '現在的兩人，即使是一瞬間的心意相通，也能嘗得喜悅。'),
(27, '兩人的關係在轉換時期。發生了大變動的時候，靜靜地注視轉折點吧。'),
(29, '無論是好是壞，兩人的關係都即將要出現一個結果，之後則是新的開始。'),
(31, '兩人關係即使當下困難重重，你仍然從其中尋覓到的平靜，並接受了。'),
(33, '兩個人關係上沒有大變化。在下一步發展中，一點點慢慢觀察吧。'),
(35, '因為突發性事件，雙方的關係現在，很可能會出現重大的變化。且它很可能是不能迴避的。'),
(37, '現在兩人的狀態傾向不安定。未來變成怎麼樣，仍無法預測。'),
(39, '兩人到現在為止的關係，累積了一些問題，且逐漸浮現了。一直無法解決的問題，答案將呼之欲出。'),
(41, '現在兩人之間貌似還存在隔閡的樣子。但，現在兩人有必要保持距離。'),
(43, '關係停滯的時期。你發現了兩人的關係停滯了。'),
-- 逆位的現狀解釋
(2, '兩人現在處於非常不穩定的狀態。某一方或兩人都在迴避承擔關係中的責任。'),
(4, '兩人目前的交往無法穩定...似乎某一方並不想要有正式的關係。'),
(6, '兩人的基於各自的幻想構築了關係。卻沒能考慮到對方的狀況和心情。'),
(8, '你的心意尚無法傳達給對方。他的興趣似乎在別的地方。'),
(10, '兩人關係表現出了幼稚或任性。或許都仍在考慮著自我滿足。'),
(12, '兩個人走進了死胡同。也許這是因為某方內心的固執造成的。'),
(14, '兩人的關係瀕臨崩壞，你卻不能接受，仍在掙扎。'),
(16, '現在兩人不知道該如何去尋找目標。但也有可能是滿足於當下的狀態。'),
(18, '兩人面臨著迷惑。不能決斷是否應該將自己的心願付諸實行。'),
(20, '兩人各自內心有自己的想法，不能如願的關係讓人感到疲憊。'),
(22, '兩個人的關係處在不平衡的狀態。有可能是因為你無法跟上對方的變化。'),
(24, '若兩人的關係面臨著問題，還會持續一段時間。還不是出現結論的時候。'),
(26, '你似乎不想直面兩人的現狀。又或者說兩人都想從問題上轉移視線。'),
(28, '兩人無法正視現況。都有無法直視的問題吧。'),
(30, '兩人的關係明明不是改變的時候，某方卻意圖改變狀況。'),
(32, '兩人的關係有些不對。那應當是相互期望的東西，卻相悖了的原因。'),
(34, '關係被自己的行動被束縛著，但雙方或許都注意到了這個狀況。'),
(36, '關係已經一去不復返了，但似乎還不想承認這想法。'),
(38, '兩個人的關係有點陷入僵局。「想這樣」這種自己的想法可能傳達不到給對方。'),
(40, '常識太過拘束、關係無法前進的樣子。試著用更自由地角度考慮彼此的關係吧。'),
(42, '兩人實現了不可能的事情，就像做夢一樣。還無法接受現實吧。'),
(44, '兩人意圖導致的結果將漸漸而來，下個階段迎來。再次新的開始。'),
-- 正位的未來解釋
(45, '兩人的關係，將寄希望於遙遠的未來，由於你獻身性質的愛而得以培育。'),
(47, '兩個人的關係將變得豐厚充盈。在一起的時候，兩人都能感到放鬆和愜意。'),
(49, '預感到兩人的關係即將沿著你期望的樣子來發展。'),
(51, '兩人從此將迎來新的開始。你已經準備好了如何傳遞自己的心意。'),
(53, '兩人的關係將迎來一個完結的節點。這之後，將迎來新的開始。'),
(55, '兩人的關係也許到達選擇的時機。按照你的心之所向前進吧。'),
(57, '兩人目前的問題迎來解決的時刻。你的心將從煩惱中解脫。'),
(59, '兩個人的關係將變得充滿生機。享受當下的快樂，向對方袒露心意。'),
(61, '兩人今後將能稍微冷靜一下。這個過程中將有新的發現。'),
(63, '兩人的關係將會變得相互束縛，儘管並非本意。'),
(65, '兩人終於決定開始前進，採取行動。這張牌象徵堅強。'),
(67, '兩人的關係將打上一個休止符，不管好壞都無法維持之前的交往。'),
(69, '兩人將迎來停滯。被固定觀念束縛，將成為改變現今關係的一步。'),
(71, '兩個人的關係將緩慢的發生變化，捨棄我執而加深理解。'),
(73, '兩人的關係將變得穩健，會有更多機會討論彼此和未來。'),
(75, '兩人將迎來轉換期，會有大的變化發生。'),
(77, '兩人的關係將帶有緊張。需要認真審視自己的心意。'),
(79, '兩人的關係將因發生的某件事而迎來巨變。'),
(81, '兩人的關係將迎來不穩定狀態，暫時看不清未來。'),
(83, '兩人的關係將維持穩定的狀態，卻缺乏樂趣。'),
(85, '兩人將出現隔閡，重新確認彼此的主張和差異十分重要。'),
(87, '兩人的未來前途未卜，但也因此暗藏不可預知的可能性。'),
-- 逆位的未來解釋
(46, '兩人的關係將出現迷惑，無法做出決斷。'),
(48, '兩人的關係將出現依賴端倪，彼此只考慮自己。'),
(50, '兩人的關係建立在虛幻上，請拿出面對現實的堅強。'),
(52, '兩個人的關係將面臨困難，需正視自己心底的慾望。'),
(54, '兩人的關係暫無定論，現在不是出結論的時候。'),
(56, '兩人完全背道而馳，固執不改將加深對立。'),
(58, '兩人的關係即將崩壞，應正視不穩定的交往。'),
(60, '兩人不打算讓關係前進，將有一段時間無法見面。'),
(62, '兩人的關係將變得膚淺，應好好溝通一次。'),
(64, '兩人都沉浸於各自想法，需認真思考真正想要什麼。'),
(66, '二人的關係早晚將迎來改變的時刻。'),
(68, '兩人的關係不會如你所想發生變化，時機未到。'),
(70, '兩人將會覺得對方難以理解，需慢慢溝通。'),
(72, '兩人的關係將走進死胡同，無法前進。'),
(74, '兩人的關係無法前進，將忍耐目前的狀況。'),
(76, '兩人的關係不能隨你意願發展，需體察對方心意。'),
(78, '兩人關係將陷入幻想中，應該多給予對方愛。'),
(80, '兩人交往穩定不下來，無法負起責任。'),
(82, '兩人的關係再也無法如從前，應進入下一階段。'),
(84, '兩人關係未達預期，重建新規的目標。'),
(86, '兩人關係可能不會進展，需要堅強的意志。'),
(88, '兩人關係試圖避開真實，心有芥蒂。'),
(89, '他失去了自信。也許他受到了很大刺激，並打算一個人來承受。'),
(91, '對方情緒非常穩定。他完全的享受和你現在的關係。'),
(93, '他現在處於不能掙脫的狀態。他似乎意識到了自己不能表達出自己的心意。'),
(95, '現在的他正以十分溫柔的心情接納對方。即便願望不能實現，他也將繼續企盼下去。'),
(97, '他似乎感到了與你之間的隔閡。也許他想先保持一下距離。'),
(99, '他現在面臨著選擇。他似乎想好了怎麼處理和你之間的關係。'),
(101, '他正為現實的東西而忙得不可開交，無法沉浸於戀愛的氣氛。'),
(103, '他的心意還定不下來。他好像還不清楚自己的想法將會變成怎樣。'),
(105, '他正認真面對著束縛到自己的苦惱和問題。不過他還是不能前進一步。'),
(107, '他的心明確的向著他喜歡的人。如果兩人是情侶的話，那他對你的心意也很有信心。'),
(109, '他正在慢慢思索著兩人之間的關係。他並不著急得出答案，而是想從容的認真考慮。'),
(111, '他感到事態正朝著自己的預想發展，而且，那也正是他想要的。現在他正眺向遠方。'),
(113, '現在的他非常的不安。讓他不安的，是對方心意以及未來的不可揣摩。'),
(115, '現在的他對和你在一起感到充實。他應該期待著這一狀態持續。'),
(117, '現在的他擁有朝向目標前進的強烈意志，非常值得依賴。'),
(119, '現在的他，相比起兩人的關係更關注自己。他想探尋自己今後到底想何去何從。'),
(121, '現在的他只是被動的接受兩人的現狀。心情上處於痛苦的時候，不過他可以挺過去。'),
(123, '現在的他期望的是謹慎有序的交往。對於自己的心要被誰奪去，或許他有一些恐懼。'),
(125, '他覺得他和你的心意對等平衡，現在的他應該沒有任何不滿。'),
(127, '他正冷靜的守望著兩人的關係。他似乎感覺到快是要出結果的時候。'),
(129, '他的心意正在發生重大的變化。似乎他意識到已不能維持以往的想法。'),
(131, '現在，他享受著和你相處的每一個當下。他沒有隱藏自己的心意，而是向你坦呈出來。'),

-- 逆位的對方的想法解釋
(90, '他似乎覺得你沒有理解到他的想法，並為此感到不滿。'),
(92, '他似乎一直對不可能實現的事情抱有夢想。或者相反，也許他是不想做徒勞無謂的事。'),
(94, '他的想法已經較之前發生了改變，自己卻沒有意識到這一點。'),
(96, '他把自己封到殼裡了。對於不能如願發展的現實，可能他感到了厭倦。'),
(98, '他的情緒越來越任性起來。這張牌顯示了他想被女性寵愛的依賴心。'),
(100, '現在的他，似乎覺得能享受當下每一刻的快樂就好。他不想被任何人束縛。'),
(102, '他不能完全接受兩人的現狀。對於進展的不如人願，他不能掩飾焦灼。'),
(104, '他有一點點焦灼。想儘量扭轉不能改變的現狀。'),
(106, '他正處在被動的狀態。他不打算主動行動，只是靜靜的等待答案。'),
(108, '他正在搖擺中。或許他急著想快些得出本不應著急的結論。'),
(110, '現在的他並不打算搞清楚自己的情緒。他的心意就是含混曖昧的。'),
(112, '他對於事態未能按照自己的意願進行，懷有一些遺憾。'),
(114, '他的心情很陷入僵局。被自己心中想這樣做的想法拘泥所束縛。'),
(116, '現在的他自說自話，不打算好好捕捉對方的情緒。'),
(118, '他沒有辦法接受自己造成的失敗以及自信的失去。'),
(120, '現在的他覺得表達自己的心意還為時過早。這也是源於他的缺乏自信。'),
(122, '現在的他好像不想背負責任。可能他不想面對現實。'),
(124, '現在的他不可倚賴。他不能自行思考發起行動。'),
(126, '他隱藏自己的心意。或許他害怕說出真相。'),
(128, '現在的他有一點任性，也許他打算把自己的意願強加給你。'),
(130, '現在的他走進了死胡同，他被自己內心固執的想法束縛著。'),
(132, '他對自己的構思無法如願似乎有些留戀。也許會不甘放棄。');
