version: '3.8'

services:
  web:
    image: tg_bot:latest
    container_name: tg_bot
    restart: always
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: tg_bot
      DATABASE_USER: root
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "80:80"
    networks:
      - prod-network

networks:
  prod-network:
    external: true
