-- 刪除表格如果已經存在
DROP TABLE IF EXISTS bots;

-- 創建 bots 表
CREATE TABLE bots
(
    bot_id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    bot_username VARCHAR(255) NOT NULL,
    bot_token    VARCHAR(512) NOT NULL,
    description  VARCHAR(512),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
